/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package draw;

import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Contreras
 */
public class Mapa_TSP extends javax.swing.JFrame {

    Panel panela;
    public static Recorrido dialog;
    public static boolean precio = false;
    public static boolean ruta = false;
    public static boolean recorridox = false;
    public static boolean dibujar_ruta = false;
    public static boolean ventana_recorrido = true;

    /**
     * Creates new form NewJFrame
     */
    public Mapa_TSP() {
        initComponents();
        this.setSize(738, 550);
        this.setResizable(false);
        this.setTitle("TSP - Carlos Contreras");
        this.setLocationRelativeTo(null);
        panela = new Panel(Mapa_TSP.panel.getSize());
        Mapa_TSP.panel.add(panela);
    }

    // override update
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenuItem();
        edicion = new javax.swing.JMenu();
        deshacer = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenuItem();
        ver = new javax.swing.JMenu();
        precios = new javax.swing.JCheckBoxMenuItem();
        rutas = new javax.swing.JCheckBoxMenuItem();
        obtener = new javax.swing.JMenu();
        ruta_mas_corta = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        acerca_de = new javax.swing.JMenu();
        TSP = new javax.swing.JMenuItem();
        separadpr = new javax.swing.JPopupMenu.Separator();
        alansoft = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        archivo.setText("Arhivo");

        nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        archivo.add(nuevo);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        archivo.add(salir);

        menu.add(archivo);

        edicion.setText("Edición");

        deshacer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        deshacer.setText("Deshacer");
        deshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deshacerActionPerformed(evt);
            }
        });
        edicion.add(deshacer);

        modificar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        edicion.add(modificar);

        menu.add(edicion);

        ver.setText("Ver");

        precios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        precios.setText("Precios");
        precios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                preciosItemStateChanged(evt);
            }
        });
        ver.add(precios);

        rutas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        rutas.setText("Rutas");
        rutas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rutasItemStateChanged(evt);
            }
        });
        ver.add(rutas);

        menu.add(ver);

        obtener.setText("Obtener");

        ruta_mas_corta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        ruta_mas_corta.setText("Ruta mas corta");
        ruta_mas_corta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta_mas_cortaActionPerformed(evt);
            }
        });
        obtener.add(ruta_mas_corta);
        obtener.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Matriz de adyacencias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        obtener.add(jMenuItem1);

        menu.add(obtener);

        acerca_de.setText("Acerca de...");

        TSP.setText("TSP");
        TSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSPActionPerformed(evt);
            }
        });
        acerca_de.add(TSP);
        acerca_de.add(separadpr);

        alansoft.setText("Alansoft");
        alansoft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alansoftActionPerformed(evt);
            }
        });
        acerca_de.add(alansoft);

        menu.add(acerca_de);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMouseClicked

        Mapa.mouseclicked(evt);
        panel.repaint();
        Mapa.ruta.clear();
        if (recorridox) {
            dialog.setVisible(false);
        }

        Mapa.costo = 0;
        ventana_recorrido = true;
        dibujar_ruta = false;
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMouseClicked

    private void ruta_mas_cortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta_mas_cortaActionPerformed
        if (ventana_recorrido) {

            Mapa.rutacorta();
            Mapa.costo = 0;
            Mapa.get_costo();
            panel.repaint();
            recorridox = true;
            dibujar_ruta = true;
            dialog = new Recorrido(new javax.swing.JFrame(), false);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    Mapa_TSP.ventana_recorrido = true;
                    Mapa.ruta.clear();
                    dialog.setVisible(false);
                }
            });
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ya ha calculado la ruta mas corta");
        }
        ventana_recorrido = false;
      
        // TODO add your handling code here:
    }//GEN-LAST:event_ruta_mas_cortaActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        Mapa.Cuidades.clear();
        Mapa.ruta.clear();
        Mapa.reset_counters();
        if (recorridox) {
            dialog.setVisible(false);
        }
        Mapa.costo = 0;
        ventana_recorrido = true;
        panel.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_salirActionPerformed

    private void preciosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_preciosItemStateChanged
        if (precios.getState()) {
            precio = true;
            panel.repaint();
        } else {
            precio = false;
            panel.repaint();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_preciosItemStateChanged

    private void rutasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rutasItemStateChanged
        if (rutas.getState()) {
            ruta = true;
            panel.repaint();
        } else {
            ruta = false;
            panel.repaint();
        }   // TODO add your handling code here:
    }//GEN-LAST:event_rutasItemStateChanged

    private void TSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSPActionPerformed
        TSP_info dialogus = new TSP_info(new javax.swing.JFrame(), true);

        dialogus.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_TSPActionPerformed

    private void deshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deshacerActionPerformed
        if (!Mapa.Cuidades.isEmpty()) {
            int pos = Mapa.Cuidades.size() - 1;
            Mapa.Estados.get(Mapa.Cuidades.get(pos).getPosición()).contador--;
            Mapa.Cuidades.remove(Mapa.Cuidades.size() - 1);
            Mapa.ruta.clear();
            panel.repaint();
            if (recorridox) {
                dialog.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nada que deshacer");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_deshacerActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        Modificar dialogo = new Modificar(new javax.swing.JFrame(), true);
        dialogo.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void alansoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alansoftActionPerformed
        About_us dialogx = new About_us(new javax.swing.JFrame(), true);
        dialogx.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_alansoftActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
                Matrix dialogus = new Matrix(new javax.swing.JFrame(), true);
                dialogus.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Mapa.add_estados();
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa_TSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Mapa_TSP().setVisible(true);

            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem TSP;
    private javax.swing.JMenu acerca_de;
    private javax.swing.JMenuItem alansoft;
    private javax.swing.JMenu archivo;
    private javax.swing.JMenuItem deshacer;
    private javax.swing.JMenu edicion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem modificar;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JMenu obtener;
    public static javax.swing.JPanel panel;
    private javax.swing.JCheckBoxMenuItem precios;
    private javax.swing.JMenuItem ruta_mas_corta;
    private javax.swing.JCheckBoxMenuItem rutas;
    private javax.swing.JMenuItem salir;
    private javax.swing.JPopupMenu.Separator separadpr;
    private javax.swing.JMenu ver;
    // End of variables declaration//GEN-END:variables
}
